language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.1"
  - "3.2"
  - "pypy"
install:
  - "pip install -r requirements.txt --use-mirrors"
  - "pip install . --use-mirrors"
script: nosetests --with-doctest
branches:
  only:
    - master
